### PR TITLE
STRIPES-520: Updated React version to 16.3

### PR DESCRIPTION
**Pull request by doytch**

### CODE REVIEW

**Comment by doytch** [comment]
ESLint can have React-related rules, right? And when the React API changes across versions, those rules may be impacted. E.g., the preferred way to write React components changed from `React.createComponent` to `class ___ extends Component`.

Or if someone wanted to write super strict linter rules in 16.3 forbidding `componentWillReceiveProps` and `componentWillUpdate` but _not_ have those trigger for projects still using <16.2.

**Comment by MikeTaylor** [comment]
Surely that's the job of `eslint-plugin-react`, though? I'm still not seeing why ESLint, which doesn't even have a UI, depends on React _itself_, rather than just a module with rules about what constitutes good React style.

**Comment by doytch** [comment]
Yeah but where do you configure it? It has to be somewhere, so I guess they just decided to keep it all in the same config? 🤷‍♂️

**Comment by MikeTaylor** [comment]
Ooohhh, I'm sorry, I completely misunderstood what's happening here. I thought you'd found a dependency on React in the package file, and had updated that. But no.

I will diminish, and go into the West.

**Pull request merged**
