### PR TITLE
Upgrade all dependencies to latest

### PR DESCRIPTION
**Pull request by cherewaty**
Follow-up to https://github.com/folio-org/eslint-config-stripes/pull/33

Let's merge that one first.

### CODE REVIEW

**Comment by MikeTaylor** [comment]
What would be the value of doing this?

**Comment by cherewaty** [comment]
We still want to get the benefits of the ruleset iterations and bug fixes the maintainers of `eslint-plugin-jsx-a11y`, etc. are doing, but on each FOLIO repo's own schedule. This PR will get all the latest ruleset iterations, but the major version bump means we can move FOLIO repos to the new rulesets deliberately.

**Comment by MikeTaylor** [comment]
Thanks for clarifying, that makes perfect sense.

So the idea is to keep individual UI apps' `eslint-config-stripes` dependencies pinned to v2.0.3 in the immediate term, and to upgrade to v3.0.0 only when there is a deliberate choice to do so -- right?

**Comment by cherewaty** [comment]
Yep, that's exactly the intent 👌 

It'd be nice to throw a couple GitHub bots on this repo so we know when ruleset dependencies have updates; every few months is probably a good pace to cut new major releases of `eslint-config-stripes`.

**Comment by cherewaty** [comment]
Yesterday `eslint-config-airbnb` released a new version enabling `eslint` 5 support. Since I hadn't merged this PR yet, I added on that update. Going to merge and cut a `3.0.0` release. FOLIO modules can update to `eslint-config-stripes@3` and `eslint@5` whenever convenient.

**Pull request merged**
